/**
  * Created by jyothi on 8/2/17.
  */

import models.{Configuration, Mail}
import com.aascar.Mailer
import org.scalatest._

class MailerTest extends FlatSpec {

  "com.aascar.Mailer" should "send text mail to <arajajyothibabu@gmail.com>" in {

    val configuration = Configuration("smtp.gmail.com", 587, "arajajyothibabu@mail.com", "password", true)

    val mail = new Mail(
      "arajajyothibabu@gmail.com" -> "Araja Jyothi Babu",
      Seq("arajajyothibabu@gmail.com"),
      subject = "Hai Jyothi Babu Araja",
      message = "This is a Test mail generated by Mailer Scripts in Aascar Repo.!"
    )

    val mailer = new Mailer(configuration).send(mail)

    assert(true)

  }

  //TODO: richText Message

  //TODO: With Attachment

}
